global_costmap:
  global_frame: map
  update_frequency: 5.0 #2.5
  publish_frequency: 5.0 #2.5
  transform_tolerance: 0.5
  width: 6
  height: 6
  origin_x: 0.0
  origin_y: 0.0  #-7.5
  static_map: true #-7.5
  rolling_window: false
  inflation_radius: 0.60  #.40
  resolution: 0.025
  plugins:
            - {name: static,                  type: "costmap_2d::StaticLayer"}
            - {name: obstacle_layer,         type: "costmap_2d::VoxelLayer"}
            - {name: inflation,               type: "costmap_2d::InflationLayer"}
