local_costmap:
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 0.25
  static_map: false
  rolling_window: true
  width: 4.0
  height: 3.0
  #origin_x: 0 #-1.0
  #origin_y: 0 #-1.0
  resolution: 0.01 #.01
  inflation_radius: 0.5 #.01
