
obstacle_range: 5.5
raytrace_range: 6.0
footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
map_topic: /map
subscribe_to_updates: true
obstacle_layer: {observation_sources: laser_scan_sensor, origin_z: 0.0, laser_scan_sensor: {sensor_frame: base_laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}}
global_frame: map
robot_base_frame: base_link
always_send_full_costmap: true
cost_scaling_factor: 3.0